stage1_config = {
    # model configs
    'pretrained_path': None,
    'retake_training': False,
    'dim_feedforward': 1024,
    'strict_load': True,
    'nheads': 16,
    'nlayers': 16,
    'dropout': 0.1,
    'dim_model': 1024,
    # 'dim_model': 256,
    'batch_first': True,
    'n_tokens': 92076,
    # 'n_connect_comp': 46502,
    'n_connect_comp': 46714,
    'n_aux': 20,
    'n_rna_type': 33,
    # 'masking_p': 0.15,
    'masking_p': 0.0,
    'batch_size': 64,
    # 'num_workers': 1,
    'num_workers': 4,
    'context_length': 1000,
    'lr': 1e-5,
    'warmup': 1000,
    'max_epoch': 100,
    'total_steps': 100000,
    'autoregressive': False,
    'pool': None,
    'supervised_task': False,
    'learnable_pe': True,
    'organ': "everything",
    'species': True,
    'assay': True,
    'modality': False,
    'contrastive': False,

    'use_gene_id_emb': True,
    'use_homo_emb': True,
    'use_esm_emb': True,
    'use_rna_type_emb': True,
    "homo_mean_targets": [],  # "homo_mean_targets": ["gene_id", "esm"]
    "comp_mean_bias": [],  # comp_mean_bias=["gid", "homo", "rna"]
    "comp_center": [],  # optional: ["gid", "homo", "rna", "pos", "dev", "esm"]
    # 'neighbor_enhance': True,
    # 'num_neighbors': 4,  # legacy
    'use_gene_deviation': True,
    'use_cell_density': True,
    'use_dev_abs': True,
    "comp_scale": {},
    "comp_scale": {},  # optional: {"gid": 1.0, "homo": 1.0, "rna": 1.0, "esm": 1.0, "dev": 1.0, "pos": 1.0}
    'cd_weight': 0.02,
    # 'root_path': '/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST',
    'esm_emb_dim': 5120,
    # 'esm_embedding_path': '/raid/zhangchengming/BrainBeacon-master/prior_knowledge/esm2_embeddings_d5120.pt',
    'pretrain_ckpt': None,
    # 'gene_id': True,

    'use_hvg': True,
    'n_hvg': 5000,
    'hvg_log1p': False,
    'use_mean_norm': True,
    'weight_mode': 'expression',
    'expr_mode': None,
    'emb_layer': 'last',  # Stage1 bb_emb readout: 'last', 'input', or encoder layer index such as 0/1/-1
    'force_tokenize': False,
}

train_path = [
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/MERFISH_human_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/MERFISH_mouse_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/STARmap_mouse_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/SlideseqV2_mouse_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/Xenium_human_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/Xenium_mouse_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/human_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque1_1_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque1_2_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque1_3_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque1_4_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque2_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque3_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/marmoset_cortex_1_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/marmoset_cortex_2_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/marmoset_cortex_3_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/marmoset_cortex_4_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/marmoset_sagittal_1_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/mouse1_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/mouse2_parquet"
]


# train_path = [
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/MERFISH_human_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/MERFISH_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/STARmap_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/SlideseqV2_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/Xenium_human_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/Xenium_mouse_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/human_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/macaque1_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/macaque2_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/macaque3_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/marmoset_cortex_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/marmoset_sagittal_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/mouse1_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/mouse2_parquet"
# ]

# train_path = [
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/MERFISH_human_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/MERFISH_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/STARmap_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/SlideseqV2_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/Xenium_human_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/Xenium_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/human_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque1_1_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque1_2_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque1_3_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque1_4_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque2_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque3_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/marmoset_cortex_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/marmoset_sagittal_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/mouse1_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/mouse2_parquet"
# ]
