stage2_config = {
  "architecture": "OmicsFormer",
  "name": "bb_flowformer",
  "enc_mod": "flowformer",
  "enc_hid": 1024,
  "enc_layers": 4,
  "latent_mod": "vae",
  "lamda": 5.0,
  "post_latent_dim": 512,
  "dec_mod": "nbmlp",
  "dec_hid": 1024,
  "dec_layers": 2,
  'objective': 'nb',
  "model_dropout": 0.2,
  "use_hidden_pe": True,
  "pe_type": 'sin',
  "pe_weight": 1.0,
  "mask_type": 'hidden',
  "mask_node_rate": 0.75,
  "mask_feature_rate": 0.25,
  "drop_node_rate": 0.3,
  "norm": "groupnorm",
  "dataset": "BrainST",
  "epochs": 200,
  "lr": 0.0002,
  "wd": 1e-08,
  "w_li": 5.0,
  "w_en": 5.0,
  "num_clusters": 16,
  "out_dim": 19374,
  "ddp": True,
  "cat_pe": False,
  "val_num": 10,
  "max_train_cells": 50000,
  "max_batch_size": 2000,
  "max_eval_batch_size": 2000,
  "fit_only": False,  # set True when only fitting the model to get rolling checkpoints
  "sampling_mode": "spatial",
  "use_patch": True,  # Deprecated: Not used in training loop.
  "knn_k": 10,
  "center_ratio": 0.5,
  "eval_use_patch": True,
  "eval_knn_k": 5,
  "eval_center_ratio": 0.5,
  "dar": False,
  "input_covariate": False,
  "beta": [2.0, 1.5],
  "batch_mixing": False,
  "ecs": False,
  "dsbn": False,
  "dae": True,
  "batch_flip": True,
  "mask_beta": True,
  "use_pretrain": True,
  "covariate_fields": ["slice_cov", "dataset_cov", "platform_cov"],
  # "covariate_fields": None,
  "slice_num": 3000,
  "dataset_num": 300,
  "platform_num": 10,
  "gene_list": [None]
}