config_train0 = {
    'pretrained_path': None,
    'retake_training': False,
    'dim_feedforward': 768,
    'nheads': 8,
    'masking_p': 0.15,
    'nlayers': 8,
    'dropout': 0.1,
    'dim_model': 768,
    'batch_first': True,
    'n_tokens': 92076,
    'n_connect_comp': 46502,
    'n_aux': 20,
    'n_rna_type': 33,
    'batch_size': 16,
    'context_length': 1000,
    'lr': 1e-5,
    'warmup': 1000,
    'max_epoch': 100,
    'total_steps': 100000,
    'autoregressive': False,
    'pool': None,
    'supervised_task': False,
    'learnable_pe': True,
    'organ': "everything",
    'specie': True,
    'assay': True,
    'modality': False,
    'contrastive': False,
    'neighbor_enhance': True,
    'num_neighbors': 4,
    'use_esm_embedding': True,
    'ems_embedding_dim': 5120,
    'root_path': '/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST',
    'esm_embedding_path': '/raid/zhangchengming/BrainBeacon-master/prior_knowledge/esm2_embeddings_d5120.pt',
    'pretrain_ckpt': None
}

config_train = {
    'pretrained_path': None,
    'retake_training': False,
    'dim_feedforward': 1024,
    'nheads': 16,
    'masking_p': 0.15,
    'nlayers': 16,
    'dropout': 0.1,
    'dim_model': 1024,
    'batch_first': True,
    'n_tokens': 92076,
    'n_connect_comp': 46502,
    'n_aux': 20,
    'n_rna_type': 33,
    'batch_size': 16,
    'context_length': 1000,
    'lr': 1e-5,
    'warmup': 1000,
    'max_epoch': 100,
    'total_steps': 100000,
    'autoregressive': False,
    'pool': None,
    'supervised_task': False,
    'learnable_pe': True,
    'organ': "everything",
    'specie': True,
    'assay': True,
    'modality': False,
    'contrastive': False,
    'neighbor_enhance': True,
    'num_neighbors': 4,
    'use_esm_embedding': True,
    'ems_embedding_dim': 5120,
    'root_path': '/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST',
    'esm_embedding_path': '/raid/zhangchengming/BrainBeacon-master/prior_knowledge/esm2_embeddings_d5120.pt',
    'pretrain_ckpt': None,
    'gene_id': True
}

config_train2 = {
    'pretrained_path': None,
    'retake_training': False,
    'dim_feedforward': 1536,
    'nheads': 16,
    'masking_p': 0.15,
    'nlayers': 18,
    'dropout': 0.1,
    'dim_model': 1536,
    'batch_first': True,
    'n_tokens': 92076,
    'n_connect_comp': 46502,
    'n_aux': 20,
    'n_rna_type': 33,
    'batch_size': 16,
    'context_length': 1000,
    'lr': 1e-05,
    'warmup': 10000,
    'max_epoch': 100,
    'total_steps': 100000,
    'autoregressive': False,
    'pool': None,
    'supervised_task': False,
    'learnable_pe': True,
    'organ': 'everything',
    'specie': True,
    'assay': True,
    'modality': False,
    'contrastive': False,
    'neighbor_enhance': True,
    'num_neighbors': 4,
    'use_esm_embedding': True,
    'ems_embedding_dim': 5120,
    'root_path': '/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST',
    'esm_embedding_path': '/raid/zhangchengming/BrainBeacon-master/prior_knowledge/esm2_embeddings_d5120.pt',
    'pretrain_ckpt': None,
    'gene_id': True
}

train_path = [
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/MERFISH_human_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/MERFISH_mouse_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/STARmap_mouse_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/SlideseqV2_mouse_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/Xenium_human_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/Xenium_mouse_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/human_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque1_1_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque1_2_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque1_3_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque1_4_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque2_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/macaque3_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/marmoset_cortex_1_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/marmoset_cortex_2_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/marmoset_cortex_3_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/marmoset_cortex_4_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/marmoset_sagittal_1_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/mouse1_parquet",
    "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0415/mouse2_parquet"
]


# train_path = [
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/MERFISH_human_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/MERFISH_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/STARmap_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/SlideseqV2_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/Xenium_human_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/Xenium_mouse_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/human_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/macaque1_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/macaque2_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/macaque3_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/marmoset_cortex_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/marmoset_sagittal_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/mouse1_parquet",
#     # "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrain_joblib_bs16_0224/mouse2_parquet"
# ]

# train_path = [
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/MERFISH_human_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/MERFISH_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/STARmap_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/SlideseqV2_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/Xenium_human_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/Xenium_mouse_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/human_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque1_1_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque1_2_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque1_3_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque1_4_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque2_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/macaque3_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/marmoset_cortex_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/marmoset_sagittal_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/mouse1_parquet",
#     "/cpfs01/projects-HDD/cfff-c7cd658afc74_HDD/public/BrainST_pretrain/pretrainJOb_add_cdandniche0412/mouse2_parquet"
# ]
